### ISSUE TITLE
Are you keeping a version with old names ?

### ISSUE THREAD

**Issue by kounkou** [Phillip-a-richmond/AnnotateVariants#1]
Hey Phil,

Are you keeping a version of your scripts with old columns names 
or the scripts need an update ?
In the below line, the column name 'aaf_gnomad_genome_all' should be replaced with :
```bash
gnomad_genome_af_global
```

https://github.com/Phillip-a-richmond/AnnotateVariants/blob/1df4261f1b5bebc239f11bc7b9934e7ee4db3709/GeminiQueries.sh#L48

**Comment by Phillip-a-richmond** [comment]
Yes that script is deprecated. I should probably make an archive directory. Use this file instead:

[https://github.com/Phillip-a-richmond/AnnotateVariants/blob/master/GeminiQueries20180716.sh](https://github.com/Phillip-a-richmond/AnnotateVariants/blob/master/GeminiQueries20180716.sh)

**Comment by kounkou** [comment]
What about a new release ? :walking_man:
